### PR TITLE
[197724 ]-People module enhancements

### PR DESCRIPTION
**Pull request by mmaciekk**
[AB#197724](https://dev.azure.com/unicef/ICTD-HCT-MIS/_backlogs/backlog/HOPE%20Team/Stories/?workitem=197724) - Main ticket People module enhancements
[AB#197175](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/197175) - Payment Module changes
[AB#197170](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/197170) - People/People details page changes
[AB#197176](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/197176) - Registration Data Import [People]
[AB#197178](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/197178) - Payment Verfication [People]
[AB#197174](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/197174) - Targeting [People]

### CODE REVIEW

**Comment by mmaciekk** [comment]
@pavlo-mk 
Could you connect people_payment_plan_summary_pdf_template
when program.dataCollectingType is socialWorkers?
I've already created the file. 

Thanks !

**Comment by johniak** [comment]
@mmaciekk I've moved PR to Draft, updated the title, and added tickets/tasks to the initial comment. This PR will consolidate changes from all tasks associated with the main ticket.

**Comment by pavlo-mk** [comment]
> @pavlo-mk Could you connect people_payment_plan_summary_pdf_template when program.dataCollectingType is socialWorkers? I've already created the file.
> 
> Thanks !

Updated >>>
image

**Review by patryk-dabrowski — APPROVED** [review]

**Review by pavlo-mk — APPROVED** [review]
🫡🤞🤞🤞

**Pull request merged**
