### PR TITLE
fix python required version

### PR DESCRIPTION
**Pull request by johniak**

### CODE REVIEW

**Review by MarekBiczysko — APPROVED** [review]

**Comment by johniak** [comment]
> @johniak just curious why?

@domdinicola Because django-admin-sync fails to install with pdm
https://github.com/unicef/hct-mis/actions/runs/9988435667/job/27606230215#step:5:1218

**Comment by domdinicola** [comment]
we are not using the cache @wozniakpl @johniak ?

**Comment by wozniakpl** [comment]
> we are not using the cache @wozniakpl @johniak ?

we are using cache.

**Comment by domdinicola** [comment]
so why we're having an issue with requirements when it was passing in staging?

**Comment by wozniakpl** [comment]
> so why we're having an issue with requirements when it was passing in staging?

most likely, some transitive dependencies have been updated recently and aren't compatible with python 3.12.

**Comment by domdinicola** [comment]
so the image has not been frozen

**Comment by wozniakpl** [comment]
Or do you mean some versioned base image that contains only built dependencies? If so, we would create a base image with fixed dependencies, tag it (e.g., some-base-image:1.0.0), push it to our Docker registry, and update our project Dockerfile to use this base image. This would indeed help stabilize our builds and avoid issues with dependency updates, but it would require extra maintenance to update and version the base image regularly.

**Pull request merged**
