### PR TITLE
[177497] Search Enhancements: two search boxes

### PR DESCRIPTION
**Pull request by patryk-dabrowski**
[AB#177497](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/177497)

### CODE REVIEW

**Review by johniak — DISMISSED** [review]

**Review by pavlo-mk — DISMISSED** [review]

**Comment by johniak** [comment]
conflicts

**Review by pavlo-mk — APPROVED** [review]

**Review by johniak — APPROVED** [review]

**Comment by domdinicola** [comment]
well done @patryk-dabrowski

**Comment by domdinicola** [comment]
Screenshot 2024-04-26 at 11 16 53

@maciej-jaworski @patryk-dabrowski is there a way to "connect" Document Type and Document Number. To improve UX-UI

**Comment by domdinicola** [comment]
@patryk-dabrowski @maciej-jaworski can you check this?

**Comment by patryk-dabrowski** [comment]
sure, I can connect those fields

**Comment by maciej-jaworski** [comment]
@domdinicola please stop taggin me, i have nothing to do with this project

**Comment by domdinicola** [comment]
@maciej-jaworski my bad.. sorry!

**Pull request merged**
